### PR TITLE
Add subscription Form and Controller

### PR DESCRIPTION
**Pull request by stefanotorresi**
This PR adds a basic subscription Form functionality, with view templates and i18n support.

I had to change some minor things in how the service manager is configured, but BC should be ok.

### CODE REVIEW

**Comment by denyil** [comment]
hi, after composer updute  we got 

( ! ) Fatal error: Uncaught exception 'Zend\ServiceManager\Exception\InvalidServiceNameException' with message 'An alias by the name "subscriber" or "subscriber" already exists' in /Users/denyil/web/edv2/vendor/zendframework/zendframework/library/Zend/ServiceManager/ServiceManager.php on line 639
( ! ) Zend\ServiceManager\Exception\InvalidServiceNameException: An alias by the name "subscriber" or "subscriber" already exists in /Users/denyil/web/edv2/vendor/zendframework/zendframework/library/Zend/ServiceManager/ServiceManager.php on line 639
Call Stack

# Time    Memory  Function    Location

1   0.0013  234608  {main}( )   ../index.php:0
2   0.0046  392400  Zend\Mvc\Application::init( )   ../index.php:20
3   0.0092  723864  Zend\ModuleManager\ModuleManager->loadModules( )    ../Application.php:238
4   0.0240  1354712 Zend\EventManager\EventManager->trigger( )  ../ModuleManager.php:108
5   0.0241  1354768 Zend\EventManager\EventManager->triggerListeners( ) ../EventManager.php:204
6   0.0241  1356528 call_user_func ( )  ../EventManager.php:460
7   0.0241  1356560 Zend\ModuleManager\Listener\ServiceListener->onLoadModulesPost( )   ../EventManager.php:460
8   0.0244  1376360 Zend\ServiceManager\Config->configureServiceManager( )  ../ServiceListener.php:223

## 9   0.0266  1419016 Zend\ServiceManager\ServiceManager->setAlias( ) ../Config.php:138

when i remove aliases you described its ok.
'aliases' => array(
             'subscriber' => 'Mailchimp\Service\Subscriber',
        )

**Comment by stefanotorresi** [comment]
thats because you didn't apply this: https://github.com/stefanotorresi/zf2-mailchimp/commit/f9697e4c52474d024b8e903b0e09f480ad73386f#L0L26

during the merge ;)

**Comment by denyil** [comment]
composer pull from master , and its still have error

**Comment by stefanotorresi** [comment]
@denyil just wait for @aaron4m to apply the fix to his merge, meanwhile you can use my branch temporarily in composer

**Pull request merged**
